### ISSUE TITLE
Non-F77-Compatible Declarations Generated for .inc Files

### ISSUE THREAD

**Issue by jcburley** [CodethinkLabs/ofc#13]
E.g.:

```
$ cat > decl.inc
      INTEGER FOO
      PARAMETER (FOO = 2)
$ cat decl.inc
      INTEGER FOO
      PARAMETER (FOO = 2)
$ ofc --sema-tree decl.inc > decl-new.inc
$ cat decl-new.inc
```

This isn't a problem for our Fortran _compilers_ (nor **gfortran**, obviously) -- even with the command-line options we use (to get F77-like behavior and extensions).

But it's a problem for at least one of the tools we use, **f2c**, to automatically generate C **.h** files. (This conversion doesn't support **STRUCTURE**, thankfully, so we needn't worry about **TYPE**.)

Also, **ofc** _itself_ can't handle these when reading back the input.

Can **ofc** support an option (perhaps on by default for **.inc** files) to generate the older-style declarations (separate **INTEGER** and **PARAMETER**, ditto anything else like that)?

**Comment by ben-brewer-codethink** [comment]
That's just the Fortran 90 method of declaring parameters and is done as part of the modernization. OFC doesn't support this yet because we've not prioritized parsing Fortran 90, though it will in the future.
We can add a command-line flag to force Fortran 77 style separate PARAMETER statements though, that shouldn't be an issue.

**Comment by ben-brewer-codethink** [comment]
OK, I've added a command-line flag to re-print PARAMETER statements F77 style, it still does the type specification for them in F90 style, but the PARAMETER statement is on its own line.

Depending on what f2c does to generate the C headers for you, it's possible we could implement that feature in OFC to allow header generation from more modern code.

**Comment by jcburley** [comment]
Added #17 because the double colons are still there. I think this issue can be closed, however (since the PARAMETER statement being generated looks correct).
