### ISSUE TITLE
Static single assignment form

### ISSUE THREAD

**Issue by dhbaird** [CodethinkLabs/ofc#14]
Does ofc have a way of exporting this form of the parsed tree:

https://en.wikipedia.org/wiki/Static_single_assignment_form

If so, what data encoding is used?

**Comment by ben-brewer-codethink** [comment]
The semantic tree we generate is currently output as Fortran code, there is no other format. It'd be easy to output the tree in other forms, and convert them to SSA but work has not yet been done on that.
The code was designed with interface a back-end in mind, so it shouldn't be a particularly difficult problem to solve. The biggest unsolved issue with creating a tree usable by a compiler back-end is placing variables in memory as is required by EQUIVALENCE and COMMON statements.
