### ISSUE TITLE
Warnings About Unused SUBROUTINEs

### ISSUE THREAD

**Issue by jcburley** [CodethinkLabs/ofc#19]
I tried compiling a .f that contained only a SUBROUTINE program unit, and got this complaint:

```
Warning: Unused SUBROUTINE 'subrname'
```

This seems surprising, because it is certainly normal for a .f to not contain an entire program, but rather one or more subroutines (and functions, though I haven't yet tried that) that aren't referenced (used, called) by any code in just that module.

The expectation is that they'll be called by one or more programs that link in the object files that result from compiling such modules.

Is there an option to suppress such warnings, or to generally indicate that a library module, rather than an entire/complete program, is contained in the .f?

Indeed, such behavior might well make sense as a default, in which case offering options to preserve the current behavior (for the warning itself and generally to indicate that an entire/complete program is contained in the .f.

**Comment by ben-brewer-codethink** [comment]
So this is part of a global analysis pass we've added, basically you can run over multiple files and it'll warn when a subroutine is declared that's not used by any of them.
You're of course right that this will always be annoying for libraries, and it's annoying for the common use-case of running over a single file. I think the point is that we'll need a separate invocation for multiple files than we have for a single file.
For now I've made the subroutine warnings opt-in as requested here.
