### ISSUE TITLE
Support -finit-local-zero

### ISSUE THREAD

**Issue by jcburley** [CodethinkLabs/ofc#24]
gfortran supports this option. E.g.:

`init.f` contains:

```
      subroutine init
      integer i
      character*10 str
      print *, 'i=',i,' str=',str,' str(1:1)=',ichar(str(1:1))
      end
      program try_init
      call init
      end
```

```
$ gfortran -W -Wall -o init init.f
$ ./init 
 i=       32608  str= str(1:1)=           0
$ gfortran -finit-local-zero -W -Wall -o init init.f
$ ./init 
 i=           0  str= str(1:1)=           0
$
```

At the very least, this option would prevent any warnings about local variables/arrays not being initialized (except where they clearly become undefined, at some point in the code flow, and are then referenced).

Ideally, suitable DATA or equivalent would be added to the converted output so `-finit-local-zero` (or similar option in another compiler) would not be needed, and the code somewhat clarified.

**Comment by jcburley** [comment]
One of the challenges I can think of here is that a declaration, by itself, doesn't necessarily denote a variable or array -- it might denote an external function. Use of EXTERNAL in the original code can clarify that. I'm not sure what'll break, though, by outputting DATA SOMEFUNC/0/ given, say, `REAL SOMEFUNC` and no actual reference to it elsewhere in the same program unit -- but certainly the DATA statement should not be generated given a reference such as `FOO = SOMEFUNC()`.

**Comment by jcburley** [comment]
And, offhand, while it seems obvious that DATA shouldn't be generated for a declared name used solely as a dummy argument in a statement-function definition, I'm not sure how that'd interact with other use of the same name as a variable or array. (It's been a long time since I worried about such things.)

**Comment by ben-brewer-codethink** [comment]
We know when a variable is read or written, so it'd be relatively easy to add a zero-ing DATA Statement only for those declarations which are actually used and known.
My main issue with adding/using this is that it would modify the meaning of the code, some variables may intentionally not be initialized as an optimization.
Seems like this should be an option strictly for a back-end, you already state that gfortran supports this, is there a compiler that doesn't?

**Comment by jcburley** [comment]
I don't know about all the compilers we might use in the future. For now, I think we're focused on gfortran, plus our existing compilers (which must support a similar option).

But another goal of ours -- that has some bigger challenges than this -- is to move towards code that is so standards-conforming that few, if any, options need to be passed to any compiler in order for the code to work.

As far as affecting code meaning: this (adding DATA or similar) would be done only when an option (say, `--init-local-zero`) is specified, an option that ideally would have basically the same effect as done by a compiler when passed a similar option.

Of  course, with its option in effect, the compiler might decide to skip the initialization when it can see there's no need; whereas, at least theoretically, if the same compiler (without its option) is given code with additional DATA statements initializing things to zero, it might not realize there's no need.

That would be a rather strange and unfortunate choice of optimization algorithms on behalf of such a compiler, however. Essentially the developers would be telling people they should write nonconforming code that breaks without special options, because if they write conforming code, certain optimizations won't be performed.

I'm actually more concerned about how people will react when they see their beloved code filled with DATA statements initializing things to 0. Some might appreciate it; others might think it's ridiculous, because (for example) C promises to initialize local `static` variables/arrays/structures to all zeros, so why shouldn't Fortran?

**Comment by ben-brewer-codethink** [comment]
Ok, I'll add this to the TODO list. I shouldn't take long.

**Comment by ben-brewer-codethink** [comment]
There's a complication with RECORD intiialization regarding default STRUCTURE initializers, since part of the structure is initialized by default the zero-initialization must be a partial-initializer, which requires the use of the DATA statement even in otherwise f90 style code.
Or we could duplicate the default initializer in each initializer for the RECORD, but duplicating expressions like that seems like it could be messy and negates the point of the default initializer.

**Comment by ben-brewer-codethink** [comment]
A worse complication is that this is not possible for dynamically sized variables. For example if an array in a subroutine is sized based on an integer argument then it's not possible to initialize that to zero in the source printout, where it would be possible at compile-time.

**Comment by ben-brewer-codethink** [comment]
Ok, this is now implemented and can be used with the flag "--init-local-zero".

There are a number of caveats:
1. Dynamically sized arrays can't be initialized to zero in code.
2. Strings are "zero'd" by initialization to the empty string, this changes whitespace printing behaviour in some cases.
3. EQUIVALENCEd variables can't cleanly be initialized to zero, so they're currently ignored.
4. COMMON blocks can't easily be initialized to zero so they're currently ignored.
