### ISSUE TITLE
EXTERNAL statement not treated correctly

### ISSUE THREAD

**Issue by arjenmarkus** [CodethinkLabs/ofc#30]
Referring to the code at https://github.com/CodethinkLabs/ofc/issues/29:

The warnings:

Warning:volterra_627.f:413,15:
   Variable 'K' read but never written
      EXTERNAL K, G, FX
               ^
Warning:volterra_627.f:413,18:
   Variable 'G' read but never written
      EXTERNAL K, G, FX
                  ^
Warning:volterra_627.f:413,21:
   Variable 'FX' read but never written
      EXTERNAL K, G, FX
                     ^ 
indicate that the EXTERNAL statement is not properly treated.

**Comment by ben-brewer-codethink** [comment]
We have a patch in the pipeline to fix this, but I'll mark it as a bug until resolved.

**Comment by arjenmarkus** [comment]
Good to hear that.

There may be sources out there that can really stress-test OFC :). The use
of EXTERNAL like the ones I reported is typical for general numerical
solvers - the current Fortran standard has much better solutions for it.

Regards,

Arjen

2016-09-07 11:27 GMT+02:00 Ben Brewer notifications@github.com:

**Comment by violetamenendez** [comment]
This should now be fixed in: 479c6b9c3774697b4352535abfd4754ee23efe09
