### ISSUE TITLE
Some variables are flagged incorrectly as not being written to

### ISSUE THREAD

**Issue by arjenmarkus** [CodethinkLabs/ofc#31]
Referring to the code at #29:

The warning:
Warning:volterra_627.f:415,39:
   Variable 'U' read but never written
      DOUBLE PRECISION RELERR, ABSERR, U, DIFF, K, G, FX 

indicates that the analysis of read/write actions is not quite waterproof: the variable in question is set in the subroutine VE1 (line 740 of the source file). Indeed it is not set in the calling program unit.

**Comment by violetamenendez** [comment]
Issue fixed with commit f9e5ffd388779c5de8e5d7f157d4ec815e337209

We now have a specific structure for function and subroutine call arguments, and we mark subroutine arguments as possibly used as we can't really know if they are written to in the call.
