### ISSUE TITLE
Arguments of type function or subroutine not recognised correctly

### ISSUE THREAD

**Issue by arjenmarkus** [CodethinkLabs/ofc#32]
Referring to the code at #29:

The warnings:
Warning:volterra_627.f:711,25:
   Incompatible argument type (REAL) in SUBROUTINE call, expected FUNCTION.
          CALL VE1(K, G, FX, M1, KA, NEPS, RELERR, ABSERR, XL, X, XOUT, 

and
Warning:volterra_627.f:2649,14:
   Incompatible argument type (REAL) in SUBROUTINE call, expected SUBROUTINE.
   10 CALL DE(F, G, FX, NEPS, NEQN, KA, BMA, Y, T, TOUT, RELERR, 

indicate that passing function and subroutine names as arguments is not properly recognised.

**Comment by violetamenendez** [comment]
Hi,

This is fixed now with the commit: a15ebd84015d80bf002bb277d6868c682ce0f2d1
It changes how LHS types are handled, which was giving back the wrong decl types when being compared with the argument types.

There's still a small issue with EXTERNAL subroutines being marked as functions that I'm fixing at the moment. Related to this but different issue, so I'm closing this one.

Thanks for reporting.
