### ISSUE TITLE
Errors with git clone and make test

### ISSUE THREAD

**Issue by rouson** [CodethinkLabs/ofc#33]
I'm installing OFC in an upcoming release of the Sourcery Institute Linux [virtual machine](www.sourceryinstitute.org/store).  Cloning using the command in the OFC README.md returns the error message below 
```
$ git clone https://github.com/CodethinkLabs/ofc.git --recursive
Cloning into 'ofc'...
remote: Counting objects: 9923, done.
remote: Total 9923 (delta 0), reused 0 (delta 0), pack-reused 9923
Receiving objects: 100% (9923/9923), 1.92 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (8030/8030), done.
Checking connectivity... done.
Submodule 'tests' (git@github.com:CodethinkLabs/ofc-tests.git) registered for path 'tests'
Cloning into 'tests'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CodethinkLabs/ofc-tests.git' into submodule path 'tests' failed
```
which presumably explains why `make test` fails with the following error message:
```
make FRONTEND=/home/rouson/Desktop/Builds/ofc/ofc  -C tests test
make[1]: *** tests: No such file or directory.  Stop.
Makefile:83: recipe for target 'test' failed
make: *** [test] Error 2
```
Any advice?

**Comment by ctgriffiths** [comment]
Do you have an ssh key associated with your github account? I think that may be the issue and that we should switch the submodule to use the https url if others are in agreement.

To get it working in the mean time clone the main repository:

    git clone https://github.com/CodethinkLabs/ofc.git

Edit the .gitmodules file, in the root of the ofc repository, to use the https url. It should end up looking like this:

```
[submodule "tests"]
	path = tests
	url = https://github.com/CodethinkLabs/ofc-tests
```
Then run:

    git submodule sync
    git submodule init
    git submodule update

and you should be good to go.

**Comment by ben-brewer-codethink** [comment]
This should be fixed in:
https://github.com/CodethinkLabs/ofc/commit/34e39f9d059684046544c529eb61df28b86da9e5
