### ISSUE TITLE
Build now fails on 10.15: file.c: error: declaration does not declare anything

### ISSUE THREAD

**Issue by barracuda156** [CodethinkLabs/ofc#46]
```
src/./file.c:289:5: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                                __attribute__ ((fallthrough));
                                ^
1 error generated.
```
Log: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/129373/steps/install-port/logs/stdio

**Comment by ben-brewer-codethink** [comment]
The issue here is likely that your clang version is too old, but I've just committed a fix that should allow it to compile on all versions of clang/gcc.

**Comment by barracuda156** [comment]
> The issue here is likely that your clang version is too old, but I've just committed a fix that should allow it to compile on all versions of clang/gcc.

@ben-brewer-codethink Thank you!

This is on buildbots, I don’t use clang at all myself, but Catalina is rather recent, so it isn’t really too old. Also, for w/e reason only Catalina failed: all earlier OS and all later were okay.

**Comment by ben-brewer-codethink** [comment]
Weird, the attribute fallthrough is a few years old now, anyhow glad it fixed it!

**Comment by barracuda156** [comment]
@ben-brewer-codethink Just found where that was added: https://github.com/CodethinkLabs/ofc/commit/0d21bef86e63db3ca02b6b1c691daf5a62a8a2b4
Should it be somehow made conditional? Apparently some other OS wanted it to be there.

**Comment by ben-brewer-codethink** [comment]
So there's a compiler where the comment doesn't work and one where the attribute doesn't? Starting to regret this usage of -Werror, these compilers can't be trusted!

**Comment by ben-brewer-codethink** [comment]
I've removed the -Werror flag as it's clearly causing too many issues due to being a moving target.

**Comment by barracuda156** [comment]
@ben-brewer-codethink I will update `ofc` in Macports now to use the latest master.
