### ISSUE TITLE
Implicit PROGRAM statement not support

### ISSUE THREAD

**Issue by jcburley** [CodethinkLabs/ofc#8]
A Fortran main program unit needn't being with a `PROGRAM` statement, yet ofc seems to require one.

E.g. this should work:

```
      END
```

Instead, this is printed:

```
Error:ofc-tests/programs/end.f:1,6:
   Expected end of input
      end
      ^
```

If a `PRINT` statement precedes the `END` statement, ofc prints this instead of accepting it:

```
Error:ofc-tests/programs/print.f:1,6:
   Unexpected executable statement in scope.
      print *, 'this should not work'
      ^
```

**Comment by jcburley** [comment]
A simple workaround would be to add a `PROGRAM` statement to the top of the main program unit.

**Comment by ben-brewer-codethink** [comment]
I've added proper support for this, didn't realize the feature existed. Is this something you've seen used in your code?

**Comment by jcburley** [comment]
Thanks for fixing this. I don't know offhand how often it's used, though some of my one-off test programs use it, mainly because I'm too lazy to bother writing a `PROGRAM` statement for them. Certainly no library code uses it (that's all subroutines and functions, of course) -- so it's just a question of our standalone programs, of which we have many still in Fortran....
